### ISSUE TITLE
Link to blog?

### ISSUE THREAD

**Issue by WillGardella** [nicholasc69/CouchbaseConnector#3]
Consider updating the README to link to your blog on Couchbase or LinkedIn
https://blog.couchbase.com/ingesting-json-data-into-couchbase-nosql-database-using-streamsets/ 
or 
https://www.linkedin.com/pulse/ingesting-data-couchbase-nosql-database-using-nick-cadenhead

**Comment by nicholasc69** [comment]
Hi,

Thank you for the suggestion. Will do.
